version: "3.9"
services:
    web:
        build:            
            dockerfile: ./Dockerfile       
        environment:
            - "ASPNETCORE_URLS=http://+:5000"
        ports:
            - "5000:5000"
        depends_on:
            - db
    db:        
        image: mcr.microsoft.com/mssql/server:2017-CU19-ubuntu-16.04
        container_name: db
        volumes:
            - db:/var/lib/mssql
        environment:       
            - SA_PASSWORD=P@ssw0rd
            - ACCEPT_EULA=Y
        ports:
            - "1433:1433"
        expose:
            - '1433'
        restart: always
    eelasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
        container_name: elasticsearch
        volumes:
          - ./esdata:/usr/share/elasticsearch/data
        environment:
          - xpack.security.enabled=false
          - discovery.type=single-node
        ulimits:
          memlock:
            soft: -1
            hard: -1
          nofile:
            soft: 65536
            hard: 65536
        cap_add:
          - IPC_LOCK
        ports:
          - 9200:9200
          - 9300:9300
volumes:
  esdata:
    driver: local
    driver_opts:
        type: 'none'
        o: 'bind'
        device: './'
  db: